server:
  servlet:
    context-path: /app
  port: ${SERVER_PORT:8080}

spring:
  cache:
    caffeine:
      spec: 60s
  profiles:
    active: dev

app:
  pathToFile: src/main/resources/static/out/products.txt
  scheduling:
    enabled: false
    period: 60000 #ms
    priceIncreasePercentage: 10.7
    optimization: false
  rest:
    currency-service:
      host: http://localhost:8082 # host второго сервиса
      methods:
        - /api/v2/currencies # url эндпоинта с курсами для GET запроса
      mock:
        enabled: true
      file: src/main/resources/json/exchange-rate.json
  kafka:
    enabled: true

kafka:
  bootstrapAddress: localhost:9091
  groupId: group1

logging:
  level:
    root: info