server:
  servlet:
    context-path: /app
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: dev

app:
  pathToFile: src/main/resources/static/out/products.txt
  scheduling:
    enabled: false
    period: 60000 #ms
    priceIncreasePercentage: 10.7
    optimization: false

logging:
  level:
    root: info