spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate