spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${NAME:postgres}
    password: ${PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
          enabled: true
          database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
