server:
  servlet:
    context-path: /app
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: dev

app:
  pathToFile: src/main/resources/static/out/products.txt
  scheduling:
    enabled: false
    period: 60000 #ms
    priceIncreasePercentage: 10.7
    optimization: false
  rest:
    currency-service:
      host: http://localhost:8082 # host второго сервиса
      methods:
        - url: /api/v2/currencies # url эндпоинта с курсами для GET запроса
        - url: /api/v2/login/account-number # url эндпоинта для POST запроса для получения account-number
        - url: /api/v2/login/account-inn  # url эндпоинта для POST запроса для получения account-inn
      mock:
        enabled: true
      file: src/main/resources/json/exchange-rate.json

logging:
  level:
    root: info