spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: ${password:postgres}
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create
    database-platform: org.hibernate.dialect.H2Dialect