spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: ${PWD}
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      enabled: true # http://localhost:8080/app/h2-console
  jpa:
    properties.hibernate.hbm2ddl.auto: create
    database-platform: org.hibernate.dialect.H2Dialect