server:
  servlet:
    context-path: /app
  port: ${SERVER_PORT:8080}

spring.profiles.active: dev

spring:
  cache:
    caffeine:
      spec: 60s
  jpa:
    properties:
      hibernate:
        jdbc:
        # show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml

app:
  pathToFile: src/main/resources/static/out/products.txt
  scheduling:
    enabled: false
    period: 60000 #ms
    priceIncreasePercentage: 10.7
    optimization: false

  currency-service:
    stub-enabled: false
    host: http://localhost:8082 # host второго сервиса
    methods:
      get-currency: /api/v2/currencies # url эндпоинта с курсами для GET запроса
    exchangeJson: src/main/resources/json/exchange-rate.json

logging:
  level:
    root: info