apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
  namespace: arch-gur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        image: sheepkiller/kafka-manager@sha256:4e4a8c5dababf7737524c7299a627bd3c7b2715d4060a0b8ca94186317a39c47
        ports:
        - containerPort: 9000
        env:
        - name: ZK_HOSTS
          value: "zookeeper-service:2181"
